[tool.poetry]
name = "lambdapipe"
version = "0.1.0"
description = ""
authors = ["Kdunorat"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.17.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
